// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKW_nawdzWQSO6DLdwran1XGbBAVpfIS0',
    appId: '1:606855973697:web:8136274dd3a86432d3afc0',
    messagingSenderId: '606855973697',
    projectId: 'campuscart-devdynasty',
    authDomain: 'campuscart-devdynasty.firebaseapp.com',
    storageBucket: 'campuscart-devdynasty.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJkM6sDaUajtvftGkL0Q2S3WYqEsxWlLw',
    appId: '1:606855973697:android:2e0b228a5fc9e26fd3afc0',
    messagingSenderId: '606855973697',
    projectId: 'campuscart-devdynasty',
    storageBucket: 'campuscart-devdynasty.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3Qvs6REhEr-4gY0EGRczDzSb_4NSlq-Q',
    appId: '1:606855973697:ios:915eebc04a1c0fead3afc0',
    messagingSenderId: '606855973697',
    projectId: 'campuscart-devdynasty',
    storageBucket: 'campuscart-devdynasty.firebasestorage.app',
    iosBundleId: 'com.example.campuscart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3Qvs6REhEr-4gY0EGRczDzSb_4NSlq-Q',
    appId: '1:606855973697:ios:915eebc04a1c0fead3afc0',
    messagingSenderId: '606855973697',
    projectId: 'campuscart-devdynasty',
    storageBucket: 'campuscart-devdynasty.firebasestorage.app',
    iosBundleId: 'com.example.campuscart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKW_nawdzWQSO6DLdwran1XGbBAVpfIS0',
    appId: '1:606855973697:web:50a1c2ea46455e6bd3afc0',
    messagingSenderId: '606855973697',
    projectId: 'campuscart-devdynasty',
    authDomain: 'campuscart-devdynasty.firebaseapp.com',
    storageBucket: 'campuscart-devdynasty.firebasestorage.app',
  );
}
